services:
  - type: web
    name: ws-sheets-bot
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: GROUP_ID
        sync: false
